#!/bin/bash
# Filename: successiveCropPDF
# Description: crop white space from pdfs
# Author: Fabian Wermelinger
# Email: fabianw@student.ethz.ch
# Created: Mon Dec 12 20:13:03 2011 (+0100)
# Version: 
# Last-Updated: Wed Dec 14 16:22:11 2011 (+0100)
#           By: Fabian Wermelinger
#     Update #: 16
# -----------------------------------------------------------------------------
# successiveCropPDF starts here
# -----------------------------------------------------------------------------
for j in *.pdf
do
    pdfcrop "$j"
done
exit 0

# -----------------------------------------------------------------------------
# successiveCropPDF ends here
# -----------------------------------------------------------------------------
